### ISSUE TITLE
HTTP Request For Stories Scraper

### ISSUE THREAD

**Issue by ghost** [Ivan-Alone/InstaStories-Saver#1]
How i can use this script for use in my website? i need HTTP Request url.

thanks :+1:

**Comment by Ivan-Alone** [comment]
It's console program, not website script. But you can explore source code to create script for your website, of cource.

**Comment by Ivan-Alone** [comment]
You can read about run this program here:
https://github.com/Ivan-Alone/InstaStories-Saver/blob/master/README.en.md
