### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by YeagGarage** [Ivan-Alone/InstaStories-Saver#2]
Иван Приветствую
Отличное решение. Сделали через официальное API?

**Comment by Ivan-Alone** [comment]
Здравствуйте. Приложение прикидывается веб-браузером и работает через запросы как будто от имени скрипта сайта.

**Comment by YeagGarage** [comment]
Классно сделали. 🙌🏻

**Comment by Ivan-Alone** [comment]
Добавьте репозиторий в избранное что ли =D

**Comment by YeagGarage** [comment]
Уже). Я как раз по Вашей логике, попробую сделать это на swift

**Comment by Ivan-Alone** [comment]
Если что у меня есть точно эта же программа, но на C++. В списке репозиториев такой же, с окончанием CPP

**Comment by YeagGarage** [comment]
О супер. !!!
