### ISSUE TITLE
Seems broken now

### ISSUE THREAD

**Issue by jz1** [Ivan-Alone/InstaStories-Saver#3]
Hi, 
This script worked before but seems broken now.
Also if i compare my login with fiddler and the login try through this script i can see also with the official login it passes a cookie with it.
While i see with this script now when i try to login it gives a cookie error on the instagram page.

Also i read the public api is disabled now, could it mayby becouse of that?
Cheers

**Comment by Ivan-Alone** [comment]
Hi!
I tested it's script now, and I find just one unfixed error, error with PHP Notice about current user's nickname in phrase "Grabbing subscribes from %nickname%'s feed...". I'll fix that, but any else is working. M/b you protected your account with phone number or etc.? This program supports login confirmation only via E-Mail, I didn't tested it with mobile phone or etc...

Public API does not affect to this program, it using WebAPI (login to Insta as Firefox browser), website of Instagram supports Stories view already 1.5 years.

Have a nice day,
Ivan Alone
